#!/usr/bin/env bash
# NeuSlice Node Installer — Mac / Linux
# Usage: curl -fsSL https://raw.githubusercontent.com/neubauet/neuslice-public/main/install.sh | bash

set -euo pipefail

COMPOSE_URL="https://raw.githubusercontent.com/neubauet/neuslice-public/main/docker-compose.yml"
INSTALL_DIR="${NEUSLICE_DIR:-$HOME/.neuslice}"
BOLD="\033[1m"; GREEN="\033[32m"; YELLOW="\033[33m"; RED="\033[31m"; GRAY="\033[90m"; RESET="\033[0m"

header()  { echo -e "\n  ${BOLD}$*${RESET}"; }
ok()      { echo -e "  ${GREEN}[OK]${RESET} $*"; }
warn()    { echo -e "  ${YELLOW}[!]${RESET}  $*"; }
fail()    { echo -e "  ${RED}[X]${RESET}  $*" >&2; exit 1; }
dim()     { echo -e "  ${GRAY}$*${RESET}"; }

ask_yn() {
    # ask_yn "Prompt" [y|n]  — returns 0 for yes, 1 for no
    local prompt="$1" default="${2:-y}"
    local hint; [[ "$default" == "y" ]] && hint="[Y/n]" || hint="[y/N]"
    local ans
    read -rp "  $prompt $hint: " ans
    ans="${ans:-$default}"
    [[ "$ans" =~ ^[Yy] ]]
}

echo ""
echo -e "  ${BOLD}NeuSlice Node Setup${RESET}"
echo -e "  ${GRAY}──────────────────────────────────────────${RESET}"
echo ""

# ── 1. Check Docker ───────────────────────────────────────────────────────────

header "Checking Docker..."

if ! command -v docker &>/dev/null; then
    warn "Docker not found. Installing..."
    curl -fsSL https://get.docker.com | sh
    ok "Docker installed"
else
    ok "Docker found: $(docker --version)"
fi

docker info &>/dev/null || fail "Docker is installed but not running. Start Docker and re-run."

docker compose version &>/dev/null || \
    fail "Docker Compose v2 required. Run: apt install docker-compose-plugin  or update Docker Desktop."
ok "Docker Compose v2 available"

# ── 2. Create install directory ───────────────────────────────────────────────

header "Setting up install directory..."
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
ok "Install directory: $INSTALL_DIR"

# ── 3. Download docker-compose.yml ────────────────────────────────────────────

header "Downloading docker-compose.yml..."
curl -fsSL --no-cache "${COMPOSE_URL}?t=$(date +%s)" -o docker-compose.yml
ok "docker-compose.yml downloaded"

# ── 4. Setup questions ────────────────────────────────────────────────────────

echo ""
echo -e "  ${GRAY}── Setup ──────────────────────────────────${RESET}"
echo ""

SKIP_ENV=false
if [ -f .env ] && grep -q "^AGENT_TOKEN=" .env; then
    EXISTING_TOKEN=$(grep "^AGENT_TOKEN=" .env | cut -d'=' -f2)
    warn "Existing .env found (token: ${EXISTING_TOKEN:0:8}...)."
    if ask_yn "Keep existing configuration?"; then
        ok "Keeping existing configuration"
        SKIP_ENV=true
    fi
fi

if [ "$SKIP_ENV" = false ]; then

    # Agent token
    echo ""
    dim "Get your Agent Token from the NeuSlice dashboard:"
    dim "Dashboard → Your Printers → Add Printer → Copy Agent Token"
    echo ""
    AGENT_TOKEN=""
    while [ -z "$AGENT_TOKEN" ]; do
        read -rp "  Paste your Agent Token: " AGENT_TOKEN
        [ -z "$AGENT_TOKEN" ] && warn "Token cannot be empty."
    done

    # Bambuddy
    echo ""
    dim "Bambuddy manages communication between NeuSlice and your printer."
    echo ""
    COMPOSE_PROFILE=""
    BAMBUDDY_URL="http://localhost:8000"

    if ask_yn "Do you already have Bambuddy installed and running?" n; then
        read -rp "  Bambuddy URL (press Enter for http://localhost:8000): " CUSTOM_URL
        [ -n "$CUSTOM_URL" ] && BAMBUDDY_URL="${CUSTOM_URL%/}"
        ok "Using existing Bambuddy at $BAMBUDDY_URL"
    else
        COMPOSE_PROFILE="bambuddy"
        BAMBUDDY_URL="http://bambuddy:8000"
        ok "Bambuddy will be installed as part of this setup"
        dim "After setup, open http://localhost:8000 to add your printer."
    fi

    # Timezone
    TZ_VAL=$(timedatectl show --property=Timezone --value 2>/dev/null || \
             readlink /etc/localtime 2>/dev/null | sed 's|.*/zoneinfo/||' || \
             echo "UTC")

    # Write .env
    cat > .env << ENV
# NeuSlice Node Configuration
# Generated by install.sh on $(date)

# Your agent token from the NeuSlice dashboard
AGENT_TOKEN=${AGENT_TOKEN}

# Bambuddy connection URL
BAMBUDDY_BASE_URL=${BAMBUDDY_URL}

# Timezone for log timestamps
TZ=${TZ_VAL}
ENV

    # Add compose profile if we're managing Bambuddy
    if [ -n "$COMPOSE_PROFILE" ]; then
        echo "" >> .env
        echo "# Enable Bambuddy container (managed by NeuSlice)" >> .env
        echo "COMPOSE_PROFILES=${COMPOSE_PROFILE}" >> .env
    fi

    chmod 600 .env
    ok ".env written"
fi

# ── 5. Pull and start ─────────────────────────────────────────────────────────

echo ""
header "Pulling Docker images (this may take a minute on first run)..."
docker compose pull

echo ""
header "Starting NeuSlice node..."
docker compose up -d

# ── 6. Done ───────────────────────────────────────────────────────────────────

echo ""
echo -e "  ${GREEN}${BOLD}✓ NeuSlice node is running!${RESET}"
echo ""

# If Bambuddy was installed, prompt them to set it up
if grep -q "^COMPOSE_PROFILES=bambuddy" .env 2>/dev/null; then
    echo -e "  ${YELLOW}Next step:${RESET} open http://localhost:8000 in your browser to add your printer to Bambuddy."
    echo ""
fi

echo "  Your printer will appear online in the NeuSlice dashboard shortly."
echo "  Updates are automatic — no action needed when NeuSlice releases new versions."
echo ""
dim "Useful commands (run from $INSTALL_DIR):"
echo "    View logs:    docker compose logs -f neuslice-agent"
echo "    Stop node:    docker compose down"
echo "    Restart node: docker compose restart"
echo ""
