#!/usr/bin/env bash
# NeuSlice Node Installer
# Usage: curl -fsSL https://neuslice.com/install.sh | bash
#
# Sets up the NeuSlice agent, Bambuddy, and Watchtower on any Linux machine
# or Mac with Docker installed. Requires only your Agent Token from the
# NeuSlice dashboard.

set -euo pipefail

COMPOSE_URL="https://raw.githubusercontent.com/neubauet/neuslice-public/main/docker-compose.yml"
INSTALL_DIR="${NEUSLICE_DIR:-$HOME/.neuslice}"
BOLD="\033[1m"
GREEN="\033[32m"
YELLOW="\033[33m"
RED="\033[31m"
RESET="\033[0m"

info()    { echo -e "${BOLD}$*${RESET}"; }
success() { echo -e "${GREEN}✓ $*${RESET}"; }
warn()    { echo -e "${YELLOW}⚠ $*${RESET}"; }
error()   { echo -e "${RED}✗ $*${RESET}" >&2; exit 1; }

echo ""
echo -e "${BOLD}NeuSlice Node Setup${RESET}"
echo "──────────────────────────────────────────"
echo ""

# ── 1. Check Docker ───────────────────────────────────────────────────────────

if ! command -v docker &>/dev/null; then
  warn "Docker not found. Installing..."
  curl -fsSL https://get.docker.com | sh
  success "Docker installed"
else
  success "Docker found: $(docker --version)"
fi

if ! docker compose version &>/dev/null; then
  error "Docker Compose v2 is required. Update Docker Desktop or install the 'docker-compose-plugin'."
fi

# ── 2. Create install directory ───────────────────────────────────────────────

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
success "Install directory: $INSTALL_DIR"

# ── 3. Download docker-compose.yml ────────────────────────────────────────────

info "Downloading docker-compose.yml..."
curl -fsSL --no-cache "$COMPOSE_URL" -o docker-compose.yml
success "docker-compose.yml downloaded"

# ── 4. Collect agent token ────────────────────────────────────────────────────

echo ""
info "You'll need your Agent Token from the NeuSlice dashboard."
info "Dashboard → Your Printers → Add Printer → Copy Agent Token"
echo ""

if [ -f .env ] && grep -q "^AGENT_TOKEN=" .env; then
  EXISTING_TOKEN=$(grep "^AGENT_TOKEN=" .env | cut -d'=' -f2)
  warn "Existing .env found with AGENT_TOKEN set (${EXISTING_TOKEN:0:8}...)."
  read -rp "Keep existing token? [Y/n]: " KEEP
  if [[ "${KEEP:-Y}" =~ ^[Yy]$ ]]; then
    success "Keeping existing configuration"
    SKIP_ENV=true
  fi
fi

if [ "${SKIP_ENV:-false}" != "true" ]; then
  while true; do
    read -rp "Paste your Agent Token: " AGENT_TOKEN
    [[ -n "$AGENT_TOKEN" ]] && break
    warn "Token cannot be empty."
  done

  # Write .env — Watchtower token is auto-generated by the container, no input needed.
  cat > .env << ENV
# NeuSlice Node Configuration
# Generated by install.sh on $(date)

# Your agent token from the NeuSlice dashboard (Settings → Your Printers)
AGENT_TOKEN=${AGENT_TOKEN}

# Timezone for log timestamps
TZ=$(timedatectl show --property=Timezone --value 2>/dev/null || echo "UTC")
ENV

  chmod 600 .env
  success ".env written"
fi

# ── 5. Pull images and start ──────────────────────────────────────────────────

echo ""
info "Pulling Docker images (this may take a minute on first run)..."
docker compose pull

echo ""
info "Starting NeuSlice node..."
docker compose up -d

echo ""
echo -e "${GREEN}${BOLD}✓ NeuSlice node is running!${RESET}"
echo ""
echo "  Your printer will appear online in the NeuSlice dashboard shortly."
echo "  Updates are automatic — no action needed when NeuSlice releases new versions."
echo ""
echo "  Useful commands:"
echo "    View logs:    docker compose -f $INSTALL_DIR/docker-compose.yml logs -f neuslice-agent"
echo "    Stop node:    docker compose -f $INSTALL_DIR/docker-compose.yml down"
echo "    Restart node: docker compose -f $INSTALL_DIR/docker-compose.yml restart"
echo ""
